language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: "pip install -r requirements.txt"
script: py.test
notifications:
  email: false
deploy:
  provider: pypi
  user: $PYPI_USER
  password:
    secure: $PYPI_PASSWORD
  on:
    branch: master
    python: '3.8'